version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:10
      - image: circleci/python:3.6 # for aws-s3

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - node_modules

jobs:
  build: # job name
    executor: default
    working_directory: ~/front
    steps:
      - checkout
      - npm_install
      
  deploy: # job name
    executor: default
    # この設定はcheckout先の指定であって、repository内のdirectoryは指定できない
    working_directory: ~/front
    steps:
      - checkout # ここでworking_directoryにcheckooutされる
      - npm_install
      - run:
          name: build
          command: yarn build
      # from と to, overwrite は circleci/aws-s3 のカスタムパラメータ
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --acl bucket-owner-full-control \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: s3://work-place-map-front/dist
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only: master