version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/front
    steps:
      - checkout
      - run: yarn install
      - run: yarn generate
      - persist_to_workspace:
          root: ~/front
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/front
    steps:
      - attach_workspace:
          at: ~/front
      - run: sudo pip install awscli
      - run: pwd
      - run: ls
      - run: aws s3 sync . s3://work-place-map-front/front --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws s3 sync . s3://work-place-map-front/front --exact-timestamps --delete --exclude "*" --include "*.js" --cache-control max-age=31536000
      # - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"